
name: build ⚙️

on: [ push, pull_request ]

jobs:
  # pypi:
  #
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - python-version: 3.7
  #           allowed_to_fail: true
  #   steps:
  #   - name: Checkout repository and submodules
  #     uses: actions/checkout@v2
  #     with:
  #       submodules: recursive
  #   - name: Install packages
  #     run: |
  #       sudo apt-get -y install pandoc libproj-dev proj-data proj-bin libgeos-dev
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install requirements 📦
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -e .
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #       if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
  #   - name: Test with pytest ⚙️
  #     run: make test
  #   # - name: Lint with flake8 ⚙️
  #   #   run: make lint
  #   #   if: matrix.python-version == 3.7
  #   # - name: Build docs 🏗️
  #   #   run: make docs
  #   #   if: matrix.python-version == 3.7

  conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda with Python ${{ matrix.python-version }}
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: defaults, conda-forge
      - name: Conda env configuration with mamba
        run: |
            conda install mamba
            mamba env create -f environment.yml
            source activate duck
            pip install -e ".[dev]"
      - name: Test with conda
        run: |
            source activate duck
            pytest tests
        continue-on-error: false
      - name: Lint with flake8 ⚙️
        run: |
            source activate duck
            flake8 duck
        if: matrix.python-version == 3.7
